### ISSUE TITLE
Close button doesn't show

### ISSUE THREAD

**Issue by diogocsc** [colorfulfool/rails-popup#1]
Where is the close button supposed to show up?

I am loading forms on popups and don't see any close button..

Any suggestions on the why?

**Comment by colorfulfool** [comment]
Here's how it should look + the markup it generates. You can also check the demo [here](https://colorfulfool.github.io/server-generated-popups/demo/).

![_ _2017-08-14_ _21_39_27](https://user-images.githubusercontent.com/1292290/29286062-59600f52-8139-11e7-8e98-5f6978c544e3.png)

Do you get any errors in JS console?

**Comment by diogocsc** [comment]
Hello, thanks for answering. No I don't get any errors in JS Console. The only div that gets generated is the popup div.

![seleccao_001](https://user-images.githubusercontent.com/1706650/29311313-5b809e1c-81a9-11e7-937a-0e1875cbfa08.png)

P.S. I am using the rails gem

**Comment by diogocsc** [comment]
After seeing you demo I added backdrop div, and noticed my css didn't have neither the backdrop neither the close button, so manually added this too to my css file. Even so, it doesn't add the close button (neither the backdrop):

![seleccao_003](https://user-images.githubusercontent.com/1706650/29312063-ce5dd31c-81ab-11e7-9e2a-eb0c385df87c.png)

**Comment by colorfulfool** [comment]
The backdrop and everything else you see in the demo comes with the lib.

My guess is that you're running an old version of it, try updating
```bash
bundle update server-generated-popups
```
You might need to restart your server afterwards.

**Comment by diogocsc** [comment]
This changed something: "Installing server-generated-popups 1.4.1 (was 1.1.10)"
And now i see the backdrop, but no longer I see the popup :-S...

I noticed that the "top" attribute is now not present on the popup div.

If I force it, the popup shows with the backdrop and the close icon ! though I need to add an extra 20px padding so that the form inputs get aligned right too.

What happened to having that top attribute on the div?

**Comment by diogocsc** [comment]
This changed something: "Installing server-generated-popups 1.4.1 (was 1.1.10)"
Close icon (and backdrop) now appears, so I am continuing this on new issue : https://github.com/colorfulfool/server-generated-popups/issues/3
