### ISSUE TITLE
Popup not showing - popup "top attribute" not defined

### ISSUE THREAD

**Issue by diogocsc** [colorfulfool/rails-popup#3]
Continues from https://github.com/colorfulfool/server-generated-popups/issues/1

This changed something: "Installing server-generated-popups 1.4.1 (was 1.1.10)"
And now i see the backdrop, but no longer I see the popup :-S...

I noticed that the "top" attribute is now not present on the popup div.

If I force it, the popup shows with the backdrop and the close icon ! though I need to add an extra 20px padding to the popup div so that the form inputs get aligned right too.

`.popup {
    padding: 20px;
}`

![seleccao_004](https://user-images.githubusercontent.com/1706650/29316067-4efee4ae-81be-11e7-9199-17be702dd65a.png)

What happened to stop having that top attribute on the popup div?

**Comment by colorfulfool** [comment]
Apparently, setting `top` without units doesn't always work. And, apparently, it shouldn't.

Update `server-generated-popups` again to get the fix. And thanks for testing!

**Comment by diogocsc** [comment]
Beautiful :+1:  Thank you for making this available !

![seleccao_005](https://user-images.githubusercontent.com/1706650/29323531-1a602e54-81d9-11e7-88aa-383cf555827e.png)

**Comment by diogocsc** [comment]
Beautiful :+1:  Thank you for making this available !

![seleccao_005](https://user-images.githubusercontent.com/1706650/29323531-1a602e54-81d9-11e7-88aa-383cf555827e.png)
